name: Publish Docker Image
on: [push]
jobs:
  build:
    docker build -t cboulanger/docker-phpfarm:latest .
  test:
    ./test.sh
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: cboulanger/docker-phpfarm
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
